 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [08/May/2023 18:34:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2023 18:34:54] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2023 18:34:57] "[32mPOST /login HTTP/1.1[0m" 302 -
[2023-05-08 18:34:57,461] ERROR in app: Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/zanez/documentos/Universidad/Tarea/Desarrollo Software Seguro/app.py", line 66, in dashboard
    return render_template('dashboard.html', username=user[1])
TypeError: 'NoneType' object is not subscriptable
127.0.0.1 - - [08/May/2023 18:34:57] "[35m[1mGET /dashboard HTTP/1.1[0m" 500 -
